"""
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

answer: 4613732
"""


def even_value_sum(limit=4000000):
    """(num) -> num

    Returns the sum of even values from a Fibonacci sequence that do not exceed 4000000

    Keyword arguments:
    limit -- The number limit (default 1000)
    """

    first_num = 0
    second_num = 1
    even_sum = 0

    while even_sum < limit:
        temp = second_num
        second_num = first_num + second_num
        first_num = temp

        if second_num % 2 == 0:
            even_sum += second_num

    return even_sum


print(even_value_sum())
